### ISSUE TITLE
HerokuのDB内容の定期バックアップ

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#105]
本格的にデータ入れ始めたので、定期的にseeds.rbに書き出さないといけない。
不正攻撃や作業ミスで泣いてしまう。

**Comment by yuina1056** [comment]
https://qiita.com/akiko-pusu/items/3847deb103c9e8346c89

**Comment by momocus** [comment]
herokuで定期Backup設定しました。
毎日AM4:00にバックアップが走ります。データは１週間保持されます。
https://data.heroku.com/datastores/a3e7a9ac-681b-4505-8cb6-76409a18344c
