### ISSUE TITLE
酒の登録ボタンをアクセスしやすい位置に配置する

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#120]
酒登録したいときにページの下までスクロールしないといけないのだるい

**Comment by yonta** [comment]
どこに置くとかっこいいか画期的なアイディアが降ってきてほしい

**Comment by momocus** [comment]
ページ上部がアクセスしやすいとは限らないからタイトル変えたよ。

スマートフォンでは、ツイッターのツイートボタンみたいな感じがよさそう。画面に追従して常に右下に存在するボタン。
