### ISSUE TITLE
チャートの正負がどちら側かわかりにくい

### ISSUE THREAD

**Issue by magu701** [momocus/sakazuki#125]
例えば、味(横軸)が-1の場合、淡麗側であるだろうとは予想できるが、せめて凡例的なものが欲しい

**Comment by yonta** [comment]
### 現状

- 味：淡（左）---濃（右）
- 香：低（下）---高（上）

### どうすべきか

- チャートの上に「濃淡高低」の字をいれる
    - Chartjsができるか
- チャートにグラデーションカラーをつけて濃淡を表す
    - 本当にわかりやすいか

**Comment by yonta** [comment]
使っててやっぱ4グラフわかりにくい。
薫酒とか爽酒とかの4図位置で色分けたりとか？
