### ISSUE TITLE
生詰めと火入れの議論をする

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#13]
どちらを`true`にするか問題

- 生詰めなら
    - `true` 生詰め、瓶火入れなし
- 瓶火入れなら
    - `true` 瓶火入れあり、生詰めではない

同じく、生貯蔵と火入れ貯蔵でどちらを`true`にするか

**Comment by yonta** [comment]
「生貯が`true`」って言われるとあまりピンとこないと思った。
前火入れと後火入れのありなし、のがピンときた。

そもそも`true` or `false`よりも、生生、前火入れ、後火入れ、二度火入れの4種のenumにしたほうが楽そう

**Comment by momocus** [comment]
火入れ状態がよくわからない場合もあるので、上記に「不明」を加えた5種のenumにするわ。
