### ISSUE TITLE
Where句による全文検索とElasticSearch全文検索の性能比較

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#131]
todo

- [x] text, string型のカラムを対象にElasticSearchで全文検索できるようにする
- [x] text, string型のカラムを対象にWhere句で全文検索できるようにする
- [x] 10000件程度のテストSeedを生成するスクリプトを作成
- [x] Where句による全文検索とElasticSearch全文検索を行い、性能を比較する
  - [x] 速度
  - [x] 精度（特にElasticSearchの方は、形態素解析のされかたによって思ったようにヒットしないことがありうる）

**Comment by yonta** [comment]
commit b8380c35594ce500e6fd2f409c90a575e3a9435c で、whereによる検索を実現した！

**Comment by momocus** [comment]
### 速度
10000件のデータで検索したところ、どちらも1秒未満で十分に早く、大きな違いは見られなかった。

### 精度
形態素解析や類義語検索、かなカナ変換ができるためElasticSearchに軍配が上がった。例えばElasticSearchでは、以下のような検索ができる。
- 「純米」で検索したとき、「純米」にヒットするが「純米吟醸」にはヒットしない
- 「りんご」で検索したとき、「林檎」にもヒットする


### 環境構築の容易さ
Where句による全文検索の方が楽。RansackというGemの使い勝手がよく、検索にソートにフィルタ機能にと便利に取り揃えられている。

ElasticSearchの方は、ElasticSearchの仕組みを理解した上で辞書を作ったりIndex構築したりと難しいものが多い。
ElasticSearchにもソートやフィルタ機能もあるらしいがまだ未検証。
また、ElasticSearch本体に加え、Kibana（Web上でElasticSearchの挙動を確認できる便利なやつ）にRedis（非同期でElasticSearchとRailsで使ってるDBの動機を取るのに使う）と複数サーバー動かす必要があるため、Dockerを使わなければ共同開発が難しそう。

**Comment by momocus** [comment]
実装の簡単さから当面はRansackでやっていきます。
とはいえSakazukiは私の勉強も兼ねてやっているので、ElasticSearchのBranchは細々と伸ばしていって、良きところで置き換えたいです。

**Comment by yonta** [comment]
ElasticSearchによる検索はどっか別な検索窓で入れておきたいね。
よくあるウェブページでもページ内全検索みたいな謎の別窓を用意している場合がある。
