### ISSUE TITLE
docker環境だと画像が表示されない

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#161]
タイトルの通り

**Comment by yonta** [comment]
uwaaaaa

**Comment by momocus** [comment]
Docker環境にImageMagic入れてないことが原因かも。
↓を参考にして試してみます。
https://qiita.com/saya1001kirinn/items/dacf5ef6b1d66ced846a

**Comment by momocus** [comment]
ImageMagick入れたら解決しました😆
