### ISSUE TITLE
「開封する/空にする」ボタンを押したとき何が起きたか、何をすればいいか分かりにくい

### ISSUE THREAD

**Issue by exoego** [momocus/sakazuki#185]
## 現状

1.「開封するボタン」を押す
2.「編集」画面が開く。開封したかっただけで別に編集したくはないんですけど、はて？と思いました
3. よーく見たら「瓶の状態」が「開封済み」になってる。なるほどね
4. が「更新」をしないと「開封済み」として保存されない

## 提案

「開封する」というアクションを押したときは「開封済み」になるのを期待しました。
編集画面を経由せず、すぐ開封済みとなったほうが開封するまでの手数が減って良いと思います。

1. 「開封済み」ボタンを押すと
2. 一覧表示を維持したまま、開封したボトルが「開封済み」に変化する

**Comment by yonta** [comment]
これはユーザの使用方法が、

- 酒を開封する
- 酒を飲む
- 酒の感想を記入する

と想定してこうしてます。
開封だけする使用方法を想定してないです。

確かにわかりにくいので、「開封・評価する」にするか。
もしくは「開封する」と「開封・評価する」にわけるかな。

**Comment by exoego** [comment]
なるほど。

1.「 開封する」を押すと、「開封済」が保存された状態で編集画面が開く
2. メッセージで「開封しました！　飲んだ評価を書いてみませんか」などと開封後にやってほしいことを誘導する

これでどうでしょうか。
また現状、瓶の状態はフォームのかなり下で気づきにくいように思います。
above-the-fold（初期表示後、スクロールしないで見れる範囲）でビンの状態が目に付きやすいようにしてもいいかもです

**Comment by yonta** [comment]
#122 でちょっと書いてた。
瓶の状態とかが下の方で見にくいのは、遷移元によって一部項目を折りたたんだりするのを検討してます。
毎回スクロールめんどい。

https://github.com/momocus/sakazuki/issues/122#issuecomment-766603412

**Comment by yonta** [comment]
開封後に評価へのリンクを用意はよさげ。
開封と評価について分けて考え直してよさそう。
確かにとりあえずあけて、忙しいから感想は後回しというシーンは対応したい。

ただ、ほしい体験の誘導というのはいらないと思ってます。
アプリ評価のように、やってほしいことを誘導するアプリではないです。
自分で使いたい人のみが使う種のアプリと認識してます。
