### ISSUE TITLE
酒データフォームの「表示義務」の意味が分からない

### ISSUE THREAD

**Issue by exoego** [momocus/sakazuki#186]
## 現状

いくつかの項目に「表示義務」とある。
「必須」は「（入力）必須」だろうとわかるが、「表示義務」はどういう意味かわかりませんでした。
「表示」はユーザーがやることではないし、「義務」といわれると「なんで？」と思ったり、面倒に感じます。
![image](https://user-images.githubusercontent.com/127635/120890431-903aa800-c63d-11eb-8f21-87e16c63da83.png)

## 提案

「入力推奨」とか、あるいは入力したくなるようモチベーションを刺激するような何かがあると良いと思いました。
たとえば「これらの項目は一覧で表示されます」とか。

**Comment by yonta** [comment]
これは「酒税法で表示義務がある」という意味です。
日本酒では、ラベルに書かなきゃいけない情報と、書かなくてもいいけど蔵が書いてる情報があります。

例えば、アルコール度数は確実に書かないといけません。
一方で絞り方は書く必要がなく、しかも同じ方法でも「雫取り」、「斗瓶囲い」と別な書き方をされます。

確かに酒税法を知ってる前提なので、なんか良い言葉がほしいですね。

**Comment by yonta** [comment]
Tooltip表示なんていいかもしれない
