### ISSUE TITLE
Cookpadのスタイルガイドを精査し、合わないものを上書き設定する

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#192]
メソッド呼び出しの括弧の省略を禁止するにはRubocopの[Style/MethodCallWithArgsParentheses](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MethodCallWithArgsParentheses)を有効にすると良さそうでした。ただし、単純に有効化するだけだと誤検出が多かったです。いくつかオプションを精査する必要があります。

_Originally posted by @momocus in https://github.com/momocus/sakazuki/issues/188#issuecomment-855454024_

**Comment by yonta** [comment]
ついでにメクラでいれたCookpadのスタイルガイドについて、合わないものは上書き設定したい

**Comment by yonta** [comment]
- `Class: RuboCop::Cop::Style::PercentLiteralDelimiters`
- 特にこだわりないから`disable` -> `enable`でいい

**Comment by yonta** [comment]
`Class: RuboCop::Cop::Style::Alias`。
`alias`の書き方。
使い方がわからないので、Cookpadのままでいいかなぁ。

**Comment by momocus** [comment]
Style/NumericLiterals
MinDigitがデフォルトでは5、Cookpadでは7。
5桁くらいから0の個数がわからくなりがちなので、デフォルトのほうがいい。

**Comment by momocus** [comment]
[Style/TrailingCommaInArrayLiteral](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInArrayLiteral)
配列の末尾のコンマのチェック。
デフォルト：配列末尾のコンマ禁止（no_comma）
Cookpad：配列が複数行にわたるとき、末尾にコンマを必ず入れる（consistent_comma）
Cookpadのままでいいと思う。

**Comment by momocus** [comment]
[Style/TrailingCommaInHashLiteral](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInHashLiteral)
ハッシュの末尾のコンマのチェック。
Arrayと同様、Cookpadのままで良い。

**Comment by momocus** [comment]
[Lint/AssignmentInCondition:](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/AssignmentInCondition)の AllowSafeAssignmentオプション
条件に代入式が書かれているとき、カッコで囲まれていれば「わかっていてやっていますよ」という扱いで許可するオプション。
Cookpadのまま、そのような書き方は許可しない。

**Comment by momocus** [comment]
> `Class: RuboCop::Cop::Style::Alias`。
> `alias`の書き方。
> 使い方がわからないので、Cookpadのままでいいかなぁ。


英語だけど[ここ](https://ernie.io/2014/10/23/in-defense-of-alias/)に書いてある情報が有用だった。
どちらもメソッド名のエイリアス用途で使うもので、より安全なのはaliasの方らしい。
aliasもalias_methodもメタメタしくて使いたくないから、ルールはどちらでも良いと思った。

**Comment by momocus** [comment]
> Style/NumericLiterals

Cookpadのままで。min_digitが7のとき、7桁未満で_入れてもrubocopには怒られない

**Comment by momocus** [comment]
> > `Class: RuboCop::Cop::Style::Alias`。
> > `alias`の書き方。
> > 使い方がわからないので、Cookpadのままでいいかなぁ。
> 
> 英語だけど[ここ](https://ernie.io/2014/10/23/in-defense-of-alias/)に書いてある情報が有用だった。
> どちらもメソッド名のエイリアス用途で使うもので、より安全なのはaliasの方らしい。
> aliasもalias_methodもメタメタしくて使いたくないから、ルールはどちらでも良いと思った。

aliasにする

**Comment by momocus** [comment]
Closed #192 via #195
