### ISSUE TITLE
Docker環境でブラウザテストできるようにする

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#202]
`docker-compose run web bundle exec rspec`をすると、Webブラウザを使うテストでFailする。docker環境にWebブラウザがないため。
Docker環境にchromeかFirefoxかを入れてブラウザテストできるようにしたい。

参考
- https://qiita.com/na-tsune/items/91630257294aa0ea4fc8
- https://qiita.com/ryohei_kh/items/2249c13d30648f50b9c8

**Comment by momocus** [comment]
Docker環境にFirefoxブラウザを入れてみたら300MBくらい（931MB -> 1.21GB）大きくなった。つらい。

**Comment by momocus** [comment]
Qiita記事の真似してwebコンテナと別にブラウザ用のコンテナ作って動かす方法にトライしたが、[selenium-webdriver](https://rubygems.org/gems/selenium-webdriver/versions/3.142.2?locale=ja) gemがruby3に非対応だったためうまくいかなかった。
selenium-webdriver のbeta版がruby3に対応していたため、それを使って試したところうまくいった。
selenium-webdriver が正式にruby3対応するまで待ってから、このIssueを片付けよう。

**Comment by momocus** [comment]
[webdrivers](https://rubygems.org/gems/webdrivers)がselenium-webdriverのバージョンに制限をかけているので、webdriversもあわせてWatchする。

**Comment by yonta** [comment]
もうできるっしょ

**Comment by momocus** [comment]
CapybaraのConfig
https://www.rubydoc.info/gems/capybara/Capybara#configure-class_method

**Comment by momocus** [comment]
`docker compose run`で動かすとDocker間ネットワークの名前解決がうまくいかない。
`docker compose up` で起動しておいて、別シェルで`docker compose exec web rspec ...`を動かすのがよさそう。
