### ISSUE TITLE
一部ページでブラウザがセキュリティ警告を出す

### ISSUE THREAD

**Issue by yuina1056** [momocus/sakazuki#275]
SSLの証明書がきれているみたいで通信の暗号化がされていないみたい。

**Comment by yonta** [comment]
詳細プリーズ。
herokuインスタンスはherokuがいい感じにしてくれるしエラーは特にない。
ローカルな何か？

**Comment by yuina1056** [comment]
再現手順:
iphoneSE2のchromeでhttps://sakazuki.herokuapp.com/sakes/157
を踏む
![331C5FF8-23B8-45DB-B9B4-F0AA1EC08169](https://user-images.githubusercontent.com/14108961/133084594-d99a7d0c-c159-4857-a35c-0a1953885a16.png)

URL部分が三角。保護されていない通信または危険な通信扱いになってる。

![266CF2CF-93E9-4829-8A84-458109F942F8](https://user-images.githubusercontent.com/14108961/133084613-a9ab7e42-5877-45d7-9887-0007ff95c9c9.png)

**Comment by yonta** [comment]
Firefox 92.0でも確認。
トップページで一部安全じゃない接続と出る

![image](https://user-images.githubusercontent.com/849256/133136155-8ca49de1-b419-4379-a850-fb8aa5a328ae.png)

**Comment by yonta** [comment]
画像のリンクが怪しい。
下記のようにhttpになっている。

- http://res.cloudinary.com/hls1kjnbj/image/upload/c_fill,h_600,w_600/v1631274280/iclpscjq210kdjzm4zrf.jpg
