### ISSUE TITLE
開封、空の日時の記録を追加したい

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#285]
統計情報とるのにあると便利そう。
なるはやで記録しておきたい。

**Comment by yonta** [comment]
マイグレーション時に、古いやつは瓶状態によって更新日時をコピーして記録しておきたいね

**Comment by yonta** [comment]
## 現状

え、precisionが6なの！？

- created_at : datetime, precision: 6, null: false
- update_at : datetime, precision: 6, null:false

## 欲しい物

### DB

- created_at : datetime, null: false
- update_at : datetime, null: false
- opened_at : datetime
- emptied_at : datetime

### create

- 未開封の酒をつくる
  - created_at = 現在時刻
  - update_at = 現在時刻
  - opened_at = null
  - emptied_at = null
- 開封済みの酒をつくる
  - created_at = 現在時刻
  - update_at = 現在時刻
  - opened_at = 現在時刻
  - emptied_at = null
- 空きの酒をつくる
  - created_at = 現在時刻
  - update_at = 現在時刻
  - opened_at = 現在時刻
  - emptied_at = 現在時刻

### 更新

- 未開封を開ける
  - update_at = 現在時刻
  - opened_at = 現在時刻
- 未開封を空にする
  - update_at = 現在時刻
  - opened_at = 現在時刻
  - emptied_at = 現在時刻
- 開封済みを空にする
  - update_at = 現在時刻
  - emptied_at = 現在時刻


### マイグレーション

- 空瓶
  - opened_atとemptied_atにupdate_atをコピー
- 開封済み瓶
  - opened_atにupdate_atをコピー
  - emptied_atはnull
- 未開封瓶
  - opened_atとemptied_atともにnull

## 注意

- 開封済み→未開封、の動作ではupdate_atのみを更新し、opened_atは更新しない
  - いつかまた未開封→開封済みになったときに、新たに正しいopened_atに更新される
- 統計を取るときは、先に瓶の状態でフィルターすることで正しく計算を行う
  - 未開封瓶でcreated_atとopened_atの差分を取らないようにする

**Comment by momocus** [comment]
いいと思う。酒瓶をどれくらいのペースで消費したかとか統計とりたいよね。
opened_atとemptied_atはviewに表示する？

**Comment by yonta** [comment]
#127

**Comment by yonta** [comment]
viewにあってユーザに見れたほうが、どれくらいで空になったかわかって面白そう。
とりあえずviewにいれるつもりで、使ってみて統計情報だけあれば良さそうなら消す感じで。

**Comment by yonta** [comment]
`precision: 6`はMySQLとPostgreSQLの互換性のためや、日付検索便利のためにデフォルトでつくらしい。
デフォルト設定を変えるほうが危ないので、`precision: 6`はキープしよう。

- <https://techtechmedia.com/precision-rails/>
- <https://qiita.com/yukke722/items/a0cae63480073b8f6495>
