### ISSUE TITLE
ページタイトルを個別に変えたい

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#288]
今はどのページを開いてもタイトル（ブラウザのタブに表示されるテキスト）が「SAKAZUKI」になっている。
BootstrapのWebサイトみたいに、ページのタイトルは個別に変えたい。
e.g. https://getbootstrap.jp/docs/5.0/getting-started/build-tools/

titleタグの中身をyeildとcontents_for（またはprivide）メソッドを使って切り替えるのがよさげ。
https://railstutorial.jp/chapters/rails_flavored_ruby?version=4.2#sec-motivation

**Comment by yonta** [comment]
close by #282

**Comment by yonta** [comment]
h1じゃなくてタイトルだった。リオープン。

**Comment by yonta** [comment]
ブラウザの進む・戻るボタンで何も情報がなくなっている状態なので、確かになんとかしたい！

![image](https://user-images.githubusercontent.com/849256/134768483-4b512fa8-7b81-4b4d-83b8-c74daf7a4826.png)
