### ISSUE TITLE
実際に酒を追加したときにわかった、dbのカラムの不具合

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#29]
以下に対応してほしい

- [x] `bindume_date`と`brew_year`を`Date`にする
    - BYに関しては`Date.new(2017, 7)`を保存することにする
        - `Date.new(2017, 7, 1)`と同等
    - 例えばBY2は令和2年7月1日～令和3年6月30日まで醸造
    - 瓶詰めは日が書かれていないので、年月だけ入力し、内部データは1日を使えばよい
- [x] `todouhuken`を`todofuken`にする
- [x] `kobo`（以下略
- [x] `tokutei_meisyo`の`nothing`を`none`にする
    - :cat2:
- [x] すでに`:unknown`などを値があるので、false nullしてnil不可にする
    - デフォルトnil不可にして、必要な場所にのみnilを許すとなおよい
    - リスト
        - `tokutei_meisho`
        - `alcohol`
        - `moto`
        - `bottle_state`
        - `hiire_state`
- [x] `is_genshu`の型を変更
    - enumでunknown/genshu/kasui
    - 現状はnil/true/falseに対応する
        - このままだと毎回`nil?`とかなるが、変更すればすべてcaseで回せる
- [x] `size : int`（単位はml）を足す
    - `price`があるなら、これもないと計算できないかもしれない

**Comment by momocus** [comment]
is_genshuをbooleanでなくするなら、カラム名を変えたい。
新しいカラム名をkasui_stateにしようと思うんだけどどう？

**Comment by momocus** [comment]
追加で

- [ ] hire_stateをhiireにする
- [ ] bottle_stateをbottle_levelにする
- [ ] is_genshuをwarimizuにする。enumで0:不明、1:加水、2:原酒

**Comment by momocus** [comment]
alcoholにデフォルト値を設定すると、ユーザーがアルコール度数を入力しなかったときにエラーを吐かず、デフォルト値（15度とか）が入ってしまうのでよくない。
alcoholはnil禁止にした上で、デフォルト値は設定しないでおく。
