### ISSUE TITLE
ログインページにnoindexをつけてGoogleなどのクローラ対象外にする

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#292]
ログイン、パスワードリセットなどのdeviseページは検索やクローラの対象外のほうがよさげ。

## やり方

- meta-tagsでできる
  - https://github.com/kpumuk/meta-tags#noindex

**Comment by exoego** [comment]
https://developers.google.com/search/docs/advanced/appearance/qualify-outbound-links?hl=ja
リンクに `rel` 属性を`<a href="/login" rel="nofollow">` などとやっておくのもオススメです。
クロールを避けてくれるので、ログインページにムダなリクエストが飛ばなくなるので。

**Comment by yonta** [comment]
まじか。
つまりログインページにnoindex属性をつけておくだけでは、他ページからリンク辿ってbotがたどり着いちゃうのか。
ログインページにnoindex属性をつけつつ、他ページからログインページにnofollow属性つけないと駄目？

**Comment by exoego** [comment]
> つまりログインページにnoindex属性をつけておくだけでは、他ページからリンク辿ってbotがたどり着いちゃうのか。

そうですね。
たとえばTwitterとかにログインページのURL書かれたりしたら、たどられるかなと。

> ログインページにnoindex属性をつけつつ、他ページからログインページにnofollow属性つけないと駄目？

noindexだけでも大丈夫だとは思います。
ログインページをリクエストしてHTMLを受け取って、noindexに気づいてインデクシングを止めるのかなと。

nofollowもやっておくと、それを理解するクローラーならムダなリクエストを省いてくれるかなと。

**Comment by yonta** [comment]
下記にあるようなrobots.txtを使う方法もある

- <https://gist.github.com/timcheadle/3761844>
