### ISSUE TITLE
faviconの設定

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#293]
ブラウザのタブやお気に入りにかわいいアイコンをつけよう！

## 必要なもの

- 16x16の画像

## やり方

- たぶんmeta-tagsでできる
  - webpackerとの兼ね合いが怪しいかも
  - https://github.com/kpumuk/meta-tags#icon

**Comment by exoego** [comment]
16x16 だけでなく、Android や iPhone のアイコンもいかがでしょうか。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by yonta** [comment]
最高。高DPIの時代、アイコンも大きくしてこう。

**Comment by yonta** [comment]
世にはfaviconジェネレータもあるので、ロゴアイコンから自動生成できそう。
144x144や256x256のような高解像度用と、16x16か32x32あたりの低解像度用の2種を用意すると幸せそう
