### ISSUE TITLE
県名ソートが日本人がよく触れているソート順になっていない

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#336]
by でこれき

すまんね、現状はあいうえおソートなんだ

## 現状

- Ransackで文字列としてソート

## ほしい

- 北海道～沖縄の順にソート
- 海外はどうする？沖縄のあと？
- 県データは数字にして県名は別DB？

**Comment by yonta** [comment]
新しい固定テーブルを追加して、joinすればいいんじゃないかな。
`1: 北海道, 2: 青森`みたいなの。

https://knowledge.cpi.ad.jp/howto-cpi/163/

**Comment by yonta** [comment]
Active_Hashを使うとDBにマスタデータ用意しなくてもいいかも

https://pikawaka.com/rails/active_hash
https://qiita.com/keitah/items/70e77e0e464fb168f5fa

**Comment by yonta** [comment]
Active_Hashだとjoin遅かったりできなかったりかも

**Comment by yonta** [comment]
素直にテーブルにtodofuken_id足したほうがいいか？
現状は都道府県だけでなくその他的に北米とか入るし。

**Comment by yonta** [comment]
ransackでjoinできそう

https://remoter.hatenablog.com/entry/2020/02/06/ransack%E3%81%AEsort_link%E3%81%A7join%E3%81%97%E3%81%9F%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%81%AE%E3%82%AB%E3%83%A9%E3%83%A0%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%9F%E3%81%84

**Comment by yonta** [comment]
idでソートしたときだけjoinする処理いれるか、そもそもsakesに都道府県codeいれちゃうか

都道府県コードについてはこちら。
総務省の大本営ページはPDFなのでとりあえずウィキペディアリンク貼っておく。
ウィキペディアの下部の外部リンクに大本一覧がある。

https://ja.wikipedia.org/wiki/%E5%85%A8%E5%9B%BD%E5%9C%B0%E6%96%B9%E5%85%AC%E5%85%B1%E5%9B%A3%E4%BD%93%E3%82%B3%E3%83%BC%E3%83%89

**Comment by yonta** [comment]
### マスターデータを作って都道府県ソートするときだけjoinする

- SQLの原則っぽくて素直
- 実装はちょっと大きくなる
  - `LEFT_OUTER_JOIN_PROCESS if query[:s].include?("todofuken")`みたいなのが入りそう

### sakesテーブルに新たにtodofuken_codeカラムを追加する

- migrateで新たなカラムを追加する
  - 追加されるデータはtodofukenの文字列によってcodeを挿入する
  - その他（北米など）には48など大きな数値をいれておく。
- ransackによるsort処理は、sort対象をtodofukenからcodeに変えるだけ。ほぼ変更が起きない。

**Comment by yonta** [comment]
どうせdbのmigrateはいるし、マスターデータ作る方がよさそうに思えてきた。

**Comment by yonta** [comment]
こんなのをrailsのseedでやる

```sql
create table todofuken_code (
  code integer not null primary key,
  todofuken varchar not null
);

insert into todofuken_code values (4, '宮城県');
insert into todofuken_code values (21, '岐阜県');
insert into todofuken_code values (23, '愛知県');
...
```

そんで、ransackでこんなSQLが生成されるようにする

```sql
select id, name, sakes.todofuken, code from sakes left outer join todofuken_code on sakes.todofuken = todofuken_code.todofuken order by code desc;
```

**Comment by yonta** [comment]
i18n化を忘れていた。今は諦めるべきでは。

**Comment by yonta** [comment]
都道府県コードを取り扱ういい感じのライブラリもある。
都道府県の生データを使わずに、こっちを使うべきでは？

https://github.com/chocoby/jp_prefecture

**Comment by yonta** [comment]
上記Ruby Gemのjp_prefectureはカスタムマッピングに対応していて、自分で地域を追加できる。
npmにあったいい感じのjp-prefectureは残念ながらカスタムマッピングに対応していない。

https://github.com/wadackel/jp-prefecture

**Comment by yonta** [comment]
問題は、「自由に文字列を入れたい」と「都道府県コードに従いソートしたい」。

1. 自由に文字列を入れたい
  - 国外にも蔵が存在しているため、都道府県で固定化できない
  - 現状の都道府県はSAKETIMESにならい「北米」や「欧州」などの地域をいれている
    - 粒度の違いがあるのは確か、今後変わっていくかも
3. 都道府県コードに従ってソートしたい
  - 都道府県のソートといえば、都道府県コードにそったソートが一般的
  - そもそも都道府県でソートできるのは嬉しいのか？？？

**Comment by yonta** [comment]
都道府県ソート削るべきでは？使ってないし

**Comment by exoego** [comment]
#482 ?

**Comment by yonta** [comment]
イエス。
別Issueで消すつもりだったのを忘れて、DBの設計を楽しんでたら同じ結論に。

消すぞ！！

**Comment by yonta** [comment]
Issue #482 で対応するのでこのIssueはクローズします
