### ISSUE TITLE
Web移行する

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#4]
どこかにサーバー作って動かす

**Comment by yonta** [comment]
#3 をしないとできない

**Comment by yonta** [comment]
サーバーはどこにしようね

1. HerokuやAWSみたいなクラウド
   - 使いすぎるとお金かかる
   - 楽
   - クラウド利用の学習になる
1. Raspberry Piで鯖を立てる
   - お金かからない
   - 鯖セットアップの学習になる
