### ISSUE TITLE
DBの日付カラムをRailsの命名規則に合わせる

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#402]
`bindume_date`はでーとでーとだ！

## やること

- DBカラム名を変える
  - `bindume_date` → `bindume_on`
- `brew_yere`はDate型だけどyearしか使っていないしそのままでも良さそうな気がする
  - それとも、`BY_on`とかに変えるか？

## 参考

- https://techracho.bpsinc.jp/hachi8833/2017_11_01/47310

**Comment by momocus** [comment]
日付はon、年はinがいいよ
bindume_date → bottled_on
brew_year → brewed_in

**Comment by yonta** [comment]
よく考えるとbrew_yearはテクニカルタームのBYから来てるし、on/inとかつけないほうがいい気がする

**Comment by yonta** [comment]
これはわざと`rice`を使わず`sakamai`を使っているのと同じ

**Comment by yonta** [comment]
最近`todofuken`はやりすぎたと思ってもいる

**Comment by yonta** [comment]
そもそも`brew_year`じゃなくて`Brewery Year`じゃん…たいぽ～～～

**Comment by yonta** [comment]
日本語だと酒造年度になるのか

https://tanoshiiosake.jp/6905

**Comment by yonta** [comment]
date型使っているけどBYは年だけで月日使ってないし、やはり`_on`でなく`brewery_year`のまま使っていこう
