### ISSUE TITLE
ActiveStorageってどうなの？

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#425]
ファイルのアップロードをするのにrails標準でActiveStorageって機能がある。
今はCarrierWaveを使ってるけど、標準の方に乗り換えた方がいいのかな？

[CarrierWave](https://github.com/carrierwaveuploader/carrierwave)
[Active Storage Overview](https://railsguides.jp/active_storage_overview.html)
[cloudinary CarrierWaveでの使い方](https://cloudinary.com/documentation/rails_carrierwave)
[cloudinary ActiceRecordでの使い方](https://cloudinary.com/documentation/rails_activestorage)

**Comment by yonta** [comment]
https://railsguides.jp/active_storage_overview.html

現状のファイル管理よりシンプルで良さげに見える。
すでにあるクラウディナリ上の画像使い回せるなら、すごくいいのでは。

**Comment by yonta** [comment]
うう、既存画像を使い回せるか怪しいぞ。
既存画像はPhotoモデルで、Sakeモデルが`has_many`している。
一方でActiveStorageは添付専用の`has_many_attached`という指定になってる。

**Comment by yonta** [comment]
https://tech.dely.jp/entry/2019/12/22/145733
逆にActiveStorageの使用をやめて、CarrierWaveにうつるいる人もいる

**Comment by yonta** [comment]
ちょっとやってみたけど、ActiveRecordの設定は簡単だけど、画像移行とCloudinary環境めちゃむずそう。

**Comment by yonta** [comment]
思ったよりつらそう。
CarrierWaveのサポートが終わるようなことがあれば移行を考えよう。
そのときは公式がMigrationガイドも出してくれると思う。

**Comment by momocus** [comment]
おっけー。調べてくれてありがとう。じゃあ当面はCarrierWaveのままってことで、このissueはcloseするね。
