### ISSUE TITLE
⚡ Turboの導入

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#437]
Rails6ではTurbolinksを使っていた。
Rails7では後継のTurboを入れるべきでは？

入れるとページ遷移時の更新量を減らして、動作速度をいい感じにしてくれるすごいやつ。
入れるほど今のページ重たいか？

**いよいよいれるべき機運！**

## やること

- deprecatedなrails-ujsの削除
  - patchやconfirmで使っている
- Turboの導入
  - 上記patchやconfirmをTurboの方法に置き換える
- deviseのTurbo対応
  - v4.9移行からTurboに対応 ~~（未リリース）~~ ついにリリース！
- 分割されたjs/cssの統合
  - ヘッダ内容の変更がない場合にのみTurbo Driveの高速化が効く
  - 現状のように各ページでjs/cssを着り変える意味がなくなるのでは？

## 作業中の不具合

- [x] ログインしようとサブミットボタンを押しても何もページ遷移しない
- [x] アカウント削除しようとしてもできない
  - 削除手順を踏むと、トップに飛ぶがログインしたまま、アカウントも生きている
- [x] kaminariページャのページ1→ページ2の遷移だけページ上部へのスクロールがしない
  - ページャ動作をTurbo Frameに変えて高速化し、どのページ遷移もスクロール移動しないようにした。
- [x] ドリンクボタンが死んでいるっぽい、テストが落ちる
- [x] 酒を削除したときのフラッシュメッセージが表示されない、テストが落ちる
- [x] js/tsとscssの各ページをやめる

**Comment by yonta** [comment]
See #447 why Turbo is reverted.
See also #436 about Stimulus.

**Comment by yonta** [comment]
Turboは何かとRSpecが落ちてデグレするし、現状の小さなシステムでは高速化の恩恵が低い。
StimulusとTurboのアップデート次第でまた検討しよう。

**Comment by yonta** [comment]
メモ

現在、drink-buttonの確認ダイアログのために@rails/ujsを使っている。
これはRails6時代の方法であり、Rails7のデフォルトには@rails/ujsが入っていない。

Rails7のデフォルトではturboを使って確認ダイアログを出している。
https://railsguides.jp/getting_started.html#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B

**Comment by yonta** [comment]
@rails/ujsはすでにdeprecatedなのでそろそろ捨てないと行けない気がしてきた。
https://github.com/rails/rails/pull/43112

**Comment by yonta** [comment]
先週deviseの未リリース内容でTurbo対応が入った。
これがリリースされたらTurbo移行すべきな機運！

### 参考

- deviseのGitHub、最新のREADMEにはTurboでの使い方が入った
  - https://github.com/heartcombo/devise
- deviseのアップグレードガイド、v4.9（未リリース）への移行手順
  - https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D

**Comment by yonta** [comment]
Turboを導入すると、confirmモーダルもカスタマイズできるかも？

https://gorails.com/episodes/custom-hotwire-turbo-confirm-modals

**Comment by yonta** [comment]
メモ
Turbo入れてる

https://github.com/momocus/sakazuki/tree/pr-turbo-issue437

**Comment by yonta** [comment]
ガイドにしたがって導入した。
ガイドに従った結果の不具合

- [ ] ログインしようとサブミットボタンを押しても何もページ遷移しない
- [ ] kaminariページャのページ1→ページ2の遷移だけページ上部へのスクロールがしない
- [ ] ドリンクボタンが死んでいるっぽい、テストが落ちる
- [ ] 酒を削除したときのフラッシュメッセージが表示されない、テストが落ちる

**Comment by yonta** [comment]
ログインはdeviseの設定を変えればいけるはず？

https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D

**Comment by yonta** [comment]
設定したら、既存のメアド・パスでログインミスになるように。どうして。

**Comment by yonta** [comment]
メアドが…ない！！！

![image](https://user-images.githubusercontent.com/849256/224667889-63ed8b5c-73e2-4cb5-98aa-395b6dd4d15b.png)

メアドの参照がうまくいってない？

**Comment by yonta** [comment]
Adminが消えた…くさはえる

**Comment by yonta** [comment]
無事復旧した。
`rails runner ./db/seeds.rb`で特定のseedsのみ読み込んで、復活ができる。

**Comment by yonta** [comment]
アカウント削除できた。
下記ブログがすべてだった。
`lint_to`と`button_to`ではTurboの指定の仕方が違う。
なんでやねん。

https://abillyz.com/moco/studies/647

**Comment by yonta** [comment]
drink_buttonは`turbo_method`指定でなおった

**Comment by yonta** [comment]
`redirect_to`にflashメッセージに便利な`notice: msg`と`alert: msg`というキーワード引数あるな。
Rails7側からもsucces/dangerよりもnotice/alert使えという圧を感じる。
現在のdeviseのnotice/alertが正しかったか。

https://railsdoc.com/page/redirect_to

**Comment by yonta** [comment]
flash、TurboでやるにはTurbo Streamを使えってこと～！？

- https://www.hotrails.dev/turbo-rails/flash-messages-hotwire
- https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/turbo-streams-fetch

**Comment by yonta** [comment]
すんごい難しいけど、TruboとRailsのHTTP処理の都合でうまく動いていない？
Turbo Streamを使うしかないのか？

ttps://github.com/hotwired/turbo-rails/issues/122#issuecomment-1217280952

**Comment by yonta** [comment]
現状の回避方法は2つ

1. 現状のflashメッセージ表示をすべてTurbo Stream移行する
  - コストは大きいが、今後の追加flashにも対応できる。追加でSPAみたいなアップデート時のflashもできる。
2. 現状のflashメッセージがうまく動かないところだけ`data-turbo: false`する
  - コストは低いが、動かないflashのみTurbo無効化する手間と負債、今後のTurboアップデートで消せるようになるかも。

**Comment by yonta** [comment]
現状試したこと

- statusをsee otherとunprossable entityにすれば動くよ → 動かない
- ファイル名にちゃんとhtmlをいれて.html.erbにすれば動くよ → 動かない
- path指定する箇所でformatにhtmlを明示的に指定すれば動くよ → 動かない

**Comment by yonta** [comment]
JSを各ページごとに分けるのとapplication.jsに統合されたのと、どちらがいいか。

- 現状：各ページごとのJS
  - TSから見て、各ページごとにDOMのidの名前空間が混じらない
    - 例えば、全部のJSを統合すると、`getElementById`で使うid名をindex.htmlとform.htmlでかぶらせてはいけない、という制約が起こる
  - 素直なページロード量は減る
    - Turbo効かせれば負ける
  - Turboが使えない
- 仮定：application.jsに統合したら
  - TurboによりJS・cssがキャッシュされるため、実際のページロード量は減る
  - 今後の簡易SPA化が楽になる
  - フロントエンドでJSを使った処理を置くとき、TSで`addEventListener("turbo:load" (_e) => {...})`を毎回書く必要がある

**Comment by yonta** [comment]
なるほどね。

全部のjsロードするのは初期読み込みが重たくなる。
できれば特定のページだけで読み込むjs、というのを管理したい。
そんな要望にも答えられるのがStimulusなんだ。

StimulusはjsとDOMの対応をラップするだけじゃない。
jsを特定のHTML要素に紐付けることができる。
すると、Turboが特定のHTML要素を読んだときだけ実行されるjsが管理できるのか。


https://logmi.jp/tech/articles/324253

**Comment by yonta** [comment]
なるほど。
ページャはTurbo Frame化すればいいのか。

https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/tutorial-2

**Comment by yonta** [comment]
ただし、空き瓶表示のチェックボックスだけはTurbo Frameでなく、Turbo Driveで処理する。

理由は、このチェックボックスは酒総量の表示を変更するから。
酒総量は現在はTurbo Frame外のH1タグに表示されている。
そのためTurbo Frameではこの更新を行えない。

解決するには、酒総量の表示位置を変更するか、Turbo Streamを使うのを検討する必要がある。
今回はやらない。

**Comment by yonta** [comment]
## Turboなしでもpatch/deleteを使う方法はないの？

- ある
  - `button_to`ならpatch/deleteが使える
    - https://railsdoc.com/page/button_to
  - ただし、ボタンなのでデザインの自由度が低い
- やはりRailsは基本post/getでデザインされている
  - `link_to`でpatch/deleteするためにujsやTurboが居ると思われる
  - ujsは`link_to`に`method: delete`などがいるといい感じのdelete formに書き換えて送信している

**Comment by momocus** [comment]
relate: #603
