### ISSUE TITLE
ログイン画面のデザイン見直し

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#457]
毎回見るのでダサいのが嫌になってきた

**Comment by yonta** [comment]
![image](https://user-images.githubusercontent.com/849256/160088841-199fd927-7b8e-4f21-92cb-d032981cacc7.png)

**Comment by yonta** [comment]
- メールアドレス・パスワードはFloating Labelかプレースホルダー
  - Floating Labelなら「email address/password」、プレースホルダーなら「mail@example.com/password」
- ログインボタンとロゴは中央揃え、他は左揃え
- 「ログインを記憶する」と各種リンクは文字サイズに小さいジャンプ率をセット

**Comment by yonta** [comment]
ユーザ招待のページも必要

**Comment by momocus** [comment]
可愛くて素敵な案ですね
