### ISSUE TITLE
📈 Chart.jsをv3系にあげる

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#461]
- Chart.js v2系を使っているけど、2016年最終リリースなのでそろそろ上げたい。
- Chart.js v3系には@typesがないけど本当にできる？

**Comment by exoego** [comment]
https://github.com/chartjs/Chart.js/tree/master/types
これかな？

**Comment by yonta** [comment]
なるほど。
@typesが見つからないと思ったら、公式レポジトリ内に入ってるのか！

**Comment by yonta** [comment]
after #584
