### ISSUE TITLE
製造年月日とBYに未来の日付を入力できてしまう

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#477]
年内であれば未来の月が入力できてしまう。例えば2022年4月現在、2022年12月の日付を入力できてしまう。
未来の日付を入力されたらValidation errorして、「未来の日付は入力できません」みたいなメッセージが出るようにしたい。

日付に関する便利なValidationを追加するgemがあった。しかしRails7非対応。
https://github.com/adzap/validates_timeliness
このgemがRails7に対応を待とう。

**Comment by yonta** [comment]
gemでチェックを入れるよりも、製造年月日の入力方式を変えたいな。

### 現状

- 年と月の2つのセレクタ
- 年は「2023 / 令和5年」で30年分
- 月は「1月」の形で1～12月分
- 入力するときに2つのセレクタ操作がまどろっこしい

### 実現したい

- 年と月が一体化したセレクタ
- 形式は「2023 / 令和5年 2月」のようにして過去に遡る
- 古酒のために30年分対応すると、セレクタ内容が多すぎるか？
  - めちゃくちゃ過去を選択する機会は少ないので、行ける気はする。

**Comment by yonta** [comment]
一体化セレクタ、難しくなーい？？？
Railsの前提は年・月・日をわけたセレクタなので、自分でセレクタ要素作らないといけなさそう。

でもそうするとselectの候補に複数valueが必要じゃない？
例えば「2023 / 令和5年 2月」って「2023年」と「2月」の2つのvalueの情報がある。
そこで、そもそもHTMLのselectって複数のvalueって埋め込めるのか？
どうせ文字列で送信されるんだし、`value=2023/02`とかにしてparseして処理するの？

**Comment by yonta** [comment]
いけるわ。
`value=2023-02-01`を持った普通のselectを使えば、Railsがうまく処理できる。
`date_select`を使わなければいいだけだった。

**Comment by yonta** [comment]
これをやっている最中に、気づいたバグをメモ

- 30年以上前の酒に編集をすると、正しい製造年月を入力できない
  - 例えば、30年物の太古酒を買うと、買った当初や次の年くらいに同様に発生しうる
  - 無限の過去入力を避けるために決め打ちにしているせい

まー、SAKAZUKIが30年稼働続けたら考えよう
