### ISSUE TITLE
indexとshowで、フッターの上部にスペースが欲しい

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#485]
indexとshowで、フッターがコンテンツにくっついててダサい。スペースが欲しい。

index
![image](https://user-images.githubusercontent.com/6294782/164479253-c9c4d3fd-5723-40f8-86df-70a408c2d618.png)

show
![image](https://user-images.githubusercontent.com/6294782/164479172-17019811-e48a-4707-bab9-374657115387.png)

**Comment by yonta** [comment]
本体のcontainerの下部にパディングいれるのがよさそうね。

関連して、コンテンツが少ないときにfooterを下部に押しやりたいというのもある。
ただし、こっちは少し難しい。

![image](https://user-images.githubusercontent.com/849256/164499187-8b549ec7-bc0a-4478-aadb-91bdb8e70dfc.png)

**Comment by yonta** [comment]
もしくはkaminariが表示されないときは、kaminari相当の幅を持った空divを挿入する

**Comment by momocus** [comment]
コンテンツが少ないときにfooterを下部に押しやるのはBootstrapExampleにあった。
https://getbootstrap.jp/docs/5.0/examples/sticky-footer/
