### ISSUE TITLE
sakeビューにおけるパーシャルビューたちのファイル命名規則を統一する

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#506]
### 現状

- ハイフンとアンダーバーの区切りが混ざってる
  - `_show_abstract.html.erb`
  - `_form-review.html.erb`

### 理想

- 揃える
- 他のライブラリのビューを見るとアンダーバーで揃えるほうがいい？

**Comment by momocus** [comment]
closed by #542 #543
