### ISSUE TITLE
debianでapt-keyが非推奨になった

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#511]
Dockerfileで`apt-key`使ってる。
debianで非推奨になったようで、こういうふうに怒られる。
```cmd
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
```

ref: https://zenn.dev/spiegel/articles/20220508-apt-key-is-deprecated

**Comment by yonta** [comment]
はい。
自分の手元のUbuntuでも遭遇して対応したので、知っていることを書いておきます。

apt-keyでは何もかもを`/etc/apt/trusted.gpg`の1ファイルにまとめて固めて管理します。
1ファイルで複数の鍵を管理すること、レポジトリごとに鍵の使い分けができないこと、が問題となりdeprecatedになりました。

今後は、まず鍵は`/etc/apt/keyrings/`ディレクトリ以下に個別の`docker.gpg`や`heroku.asc`ファイルとして配置します。
そして、aptのレポジトリ指定時に`dev [arch=... signed-by=/etc/apt/kerings/heroku.asc] http::/...`のように使う鍵を指定します。

現状は、鍵の形式が複数あること、鍵を置く位置がツールのドキュメントごとに違うこと、などがありやや混乱している状況です。
（ドキュメントによっては`/usr/share/keyrings/`に配置も見かけるけど、ここはOSの公式パッケージの管理化なので、手配置はあまり好ましくないかなと思います）

以下の方針で対応していくと良さそうです。

- 鍵の形式はバラバラでもいいので`/etc/apt/keyrings/`にまとめておく。
- apt sourcesの内容に`[signed-by=...]`を追記する
