### ISSUE TITLE
README のスクリーンショットに香りや味の評価マークがついておらず、どんな見た目か分かりにくい

### ISSUE THREAD

**Issue by exoego** [momocus/sakazuki#521]
# Current

![README](https://raw.githubusercontent.com/momocus/sakazuki/60cf9370130ad6dc2ce7427e2662276ae899b088/screenshot.png)

# Proposed

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/127635/202887134-af57dd55-ea80-4ab2-bd87-63d74a072e0c.png">

**Comment by yonta** [comment]
いい！！！
今ちょうど宮城のお酒をいっぱい買ってあるのでいいタイミング。
スクリーンショット取り直そ。
