### ISSUE TITLE
テストカバレッジが下がると容赦なくActionsがエラーする

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#524]
例えば PR #519 で起こっている。

![image](https://user-images.githubusercontent.com/849256/203274815-7fd496c0-f580-4ffe-b649-942c9868ab6e.png)

### 問題点

- リファクタで行数が減ると、見た目のカバレッジが下がりActionsがエラーとなる
- カバレッジを上げることはプロダクトの目的ではない

### どうするか

- CodecovのActionsは参考程度とし、エラーにならにようにする

**Comment by exoego** [comment]
CodeCov のフォーラムに公式メンバーからのコメントがありますが、想像のとおりので、今のところ仕様というか、計算的に当然ということのようですね。
https://community.codecov.com/t/project-coverage-decrease-on-deleted-line/2726/2

ぼくがメンテナーしてるOSSでも、CodeCov で例のようなカバレッジの低下があってもマージしてますね。

**Comment by yonta** [comment]
はい。
なのでCodeCovは計算式に従って数値を出しているだけですし、Actionsも仕様に従って失敗しているだけですね。
でもこの失敗が我々SAKAZUKIが欲しいものではないと思っています。

のであくまでもカバレッジの数値は参考までにして、Actionsが失敗報告をしないようにします。
Actionsが失敗しているのにマージする、という運用は割れ窓理論的にもテスト失敗に鈍感になる可能性があるのでよくないと思っています。

**Comment by exoego** [comment]
> 失敗報告をしないようにします。

いいんじゃないでしょうか
