### ISSUE TITLE
Github Actions のtest Jobが終わらない

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#527]
Github Actions のtest Jobが実行に6時間以上かかって終わらずに、強制終了されている様子。
https://github.com/momocus/sakazuki/actions/runs/3542603224/jobs/5948282593

また、`Selenium::WebDriver::Error::SessionNotCreatedError`が発生して複数のテストが不合格になっている模様。
```sh

Failures:

  1) Copy Sakes copied values kura and todofuken has copied kura and todofuken
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit sake_path(sake.id)

          Selenium::WebDriver::Error::SessionNotCreatedError:
            Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
          # ./spec/system/copy_sakes_spec.rb:27:in `block (2 levels) in <top (required)>'

```

ローカルで`bundle rspec`したら全てのテストが合格になる。

**Comment by momocus** [comment]
test Jobでubuntu-latestを使ってる。
https://github.com/momocus/sakazuki/blob/99d5aa110cccdd0eac983ab2a09ac8188bd7a3ec/.github/workflows/test.yml#L18-L23

Github actionsで使われるUbuntuのバージョンが20.04->22.04に上がって、firefoxが使えなくなったみたい。
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
https://zenn.dev/snowcait/articles/73e42154ed4654

試しにubuntu-20.04に書き換えたら無事テストが通った。
https://github.com/momocus/sakazuki/actions/runs/3545788799/jobs/5954226666

**Comment by yonta** [comment]
GitHub Actionsチームは今後Ubuntu 22.04のイメージにFirefoxをインストールしてくれるようです。
現在PRがレビュー中なのでそのうち入ると思う。

https://github.com/actions/runner-images/pull/6528

とりあえずの対応としてTest ActionではUbuntu 20.04でピンニングして、PRが通ったらlatestに移行するようにしよう。
