### ISSUE TITLE
画像をアップロードするときに圧縮したい

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#537]
酒の画像は高画質である必要はない。裏のラベルの文字が読める程度あればよい。

Cloudinaryの使用率は2023/01/26現在、容量10GB中の13%である。将来のことを考えるともっと圧縮したい。

**Comment by momocus** [comment]
現在SAKAZUKIアップロードされている中でも文字が小さい写真で圧縮テストしてみた。

圧縮方法：
指定したwidth x height 未満にアスペクト比を保ってリサイズするresize_to_fit メソッドを使用。
ただし、本番環境のCarrierWave::Cloudinaryではなく、ローカル環境のCarrierWave::MiniMagickにて検証した。resize_to_fit メソッドの挙動は変わらないはず。


元画像 3024x4032 /2.23MB
![bn1ecu4yuf0xxqbqwfsg](https://user-images.githubusercontent.com/6294782/219562931-0a084f8a-ed3a-4700-a7db-cdc753a1bc93.jpg)


resize_to_fit( 600, 600 ) / 257KB （サムネイルが600x600）
![bn1ecu4yuf0xxqbqwfsg600](https://user-images.githubusercontent.com/6294782/219566859-cac5bd58-ec3c-411d-a45f-0186b8c7970d.jpg)

resize_to_fit( 800, 800 ) / 301KB
![bn1ecu4yuf0xxqbqwfsg800](https://user-images.githubusercontent.com/6294782/219566903-20d163c1-636c-47f0-bd64-2d1bef25a95a.jpg)

resize_to_fit( 1000, 1000 ) / 355KB
![bn1ecu4yuf0xxqbqwfsg1000](https://user-images.githubusercontent.com/6294782/219566954-08629260-83e6-480d-95f8-36c2beb87368.jpg)

resize_to_fit( 1200, 1200 ) /  421KB
![bn1ecu4yuf0xxqbqwfsg1200](https://user-images.githubusercontent.com/6294782/219566990-c755c92e-b428-494a-aaf5-358d20373b1a.jpg)

resize_to_fit( 1400, 1400 )  / 496KB
![bn1ecu4yuf0xxqbqwfsg1400](https://user-images.githubusercontent.com/6294782/219567031-699d35a0-5772-45c0-9c39-3aa87a1c95a1.jpg)

**Comment by momocus** [comment]
resize_to_fit( 800, 800 ) がギリギリ読めるくらい。
resize_to_fit( 1200, 1200) あれば十分余裕があるかなという気持ち。

**Comment by exoego** [comment]
画像フォーマットについて WebP を検討してはいかがでしょうか。
ロスレスのPNGと比較して26%、ロスありのJPEGと比較して30%前後縮むと謳われています。
https://developers.google.com/speed/webp?hl=ja

グローバルで使われているブラウザの97%以上が対応しているそうです。
https://caniuse.com/webp

**Comment by momocus** [comment]
ウワー2.2 MBのJPGがWebPにしただけで370KBになりました。

**Comment by momocus** [comment]
間違えて関連プルリクをmasterにマージしたのでリオープン
