### ISSUE TITLE
SAKETIMESの銘柄が空白区切りだけだったのが、句点・中点でも区切るものが現れた

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#544]
終わった。

### 問題点

- SAKETIMESの複数銘柄は空白区切りのみと仮定していたが、句点（、）や中点（・）での区切りができた
- 銘柄に空白が含まれるのは海外の蔵のみと改定していたが、日本国内の蔵の代表銘柄にも空白が含まれるものが現れた

### `get_kura.rb`を動かしたあとのdiffの様子

![image](https://user-images.githubusercontent.com/849256/217185752-f7d1ccb9-9d4c-4e09-9ea8-92cbf64bf241.png)

**Comment by momocus** [comment]
地獄じゃ……
