### ISSUE TITLE
酛をStringに

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#592]
生酛、山廃、即醸酛、水酛といった言葉を調べてみたところ、どうやら酒母の製造工程の差で名前が変わるみたい。
酒母の製造の仕方なんていくらでも工夫のしようがあるため、酛のカラムはenumではなくStringにした方が良いのでは？

_Originally posted by @momocus in https://github.com/momocus/sakazuki/issues/577#issuecomment-1471548060_

**Comment by yonta** [comment]
stringは自由に入れられる分、型としての制約が弱いのでなるべく使いたくない。
enumはvalidationで多少ましな制約をつけれるので、できる箇所はなるべくenumを優先して使いたい。

現状、酛に関してはこの4つ以外を知らないし出てくる可能性がかなり低い。
作った当初も3種類以外の可能性がほぼないという議論をしてenumを採用した。
なので今回の追加を行っただけで、enumのままでいいと思う。

意識しているのは例えば季節はstringなことだと思う。
あれはstringを採用しているけど、「新酒」などをautocompleteしているのでセレクタっぽい入力ができる。
けど実態はstringなので、補完を使わずなんでも自由なものが入れられてしまう。
ただこれは季節の言葉に対して曖昧さがあるから。
例えば「ひやおろし」と同じ意味を持つ言葉には「秋あがり」がある。
この両方をユーザが入れられるように、ここはstringを採用している。

**Comment by momocus** [comment]
書いてくれてありがとう:raised_hands:
前も同じ議論した気はしてたけど、どういう結論になったかを残してなかったんだ。
