### ISSUE TITLE
蔵を入力したら自動で都道府県を入れて欲しい

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#6]
酒モデルと別に蔵モデルを作って都道府県と紐づけたら良さそう

**Comment by yonta** [comment]
# 欲しいDB

- カラム
    - 酒蔵名（株式会社一ノ蔵）
    - 都道府県（宮城県）
- あると便利かも？のカラム
    - 住所？（ほげほげ郡ほげほげ町）
    - 代表銘柄？（一ノ蔵）
    - URL？（http----）

# どうやって作るか

どこが全部載っているのか？

1. 手動で頑張る
    - 酒造組合
        - https://www.japansake.or.jp/common/outline/ichiran.html
    - 地区ごとにウェブページの構造が違うため、スクレイピングに向かない
2. 便利ページからスクレイピングする
    - SKATIMESに便利そうな一覧ページがあった
        - https://jp.sake-times.com/sakagura
    - このままでは使えない
    - Rubyスクリプト作ってでスクレイピングしてDB化しないと行けない
