### ISSUE TITLE
docker composeを立ち上げなおすと画像が消える

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#608]
public/uploadsをバインドマウントも永続化もしてないから消える

## 再現手順

1. docker compose up
2. 適当な酒を編集して画像を追加 →indexに画像がある
3. docker compose down
4. docker compose up
5. indexで画像がこんな感じのアイコンになる→🖼️ 
<img width="957" alt="スクリーンショット 2023-08-28 23 34 56" src="https://github.com/momocus/sakazuki/assets/6294782/ebbfaf4f-5c5a-425f-aaa2-ac5938cddde8">

**Comment by yonta** [comment]
そもそもpublicマウントしてなかったから、505エラーページとかも表示されない！！なんてこった！
