### ISSUE TITLE
docker composeのスリム化（js, css）

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#609]
js, cssで<<: *webしてるけど、web全部は要らなそう

**Comment by yonta** [comment]
これ、どうするのがいいんだろうね。

現状は新たなイメージを作らずに、既存イメージを使いまわしている。
既存イメージがある程度大きいし、これを1コンテナで立ち上げるのは、だいぶ無駄が多いと思う。
マウントにも問題があって、どのコンテナが./app/asset/build以下を読むのか書くのかを、
ちゃんと整理せずにイメージ設定を継承して使っている。

前者のイメージ問題は、大体以下の2つの解放かなと思う。

1. esbuildの軽量イメージを探して、それに最小限のソースをマウントして使う
2. そもそもwebイメージのコマンドを`rails server`から`foreman`のような複数exe管理に切り替える

後者のマウントの設定については、前者問題をどちらの開放をとるかに合わせて、設定を変える必要があるね。

**Comment by yonta** [comment]
個人的には開発イメージとしてwebイメージを作っているし、foremanとかでまとめたプロセス起動でいい気がする。

**Comment by momocus** [comment]
開発用だしデカくていいやと思ったのでクローズします
