### ISSUE TITLE
お品書きモード

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#61]
スタイルを変えてよりオシャレに表示したい

- オシャレなフォント
- 季節感あるオシャレな背景
- 酒の名前とスペック
- 価格（1合の原価だとウケが良さそう）

**Comment by momocus** [comment]
通常の検索をElasticSearchにして、お品書きモードだったり高度な検索モードでRansackを使えるようにするといいかも。

**Comment by momocus** [comment]
#474 にてクローズ

**Comment by momocus** [comment]
> 通常の検索をElasticSearchにして、お品書きモードだったり高度な検索モードでRansackを使えるようにするといいかも。

ElasticSearchは機能過剰ぎみだったのでHeroku移行時に削除した。
