### ISSUE TITLE
Refactor: MVCっぽくする

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#611]
Controllerにデータ変換処理があって、あまりMVC（Model, Controller, View）っぽくないつくりになってる。
MVCの考え方では、ControlerはModelとView間のデータの受け渡しに専念するのがよいらしい。

**Comment by yonta** [comment]
これはIssueよりもマイルストーンにすべきでは

**Comment by momocus** [comment]
たしかに。
これは閉じます。
