### ISSUE TITLE
🪰 連続でマージするとflyデプロイが失敗する

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#615]
そりゃそうか、deploy連打よくない。

cnacel otherしないといけない気がする！
flyへのデプロイにskip-duplicate-actionsを導入すれば解決できるはずだ！

## 起きてる様子

4m agoと5m agoのように短期で回すと、後から回したやつが落ちる。

![image](https://user-images.githubusercontent.com/849256/227910191-6c80f466-816a-4fd7-bc05-fc6d35ee52c6.png)

**Comment by exoego** [comment]
https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
GitHub が最近 beta で出したマージキューを試すのはどうでしょう。

**Comment by momocus** [comment]
何か連続マージして壊れた時、skip-duplicate-actionsだとどのマージで壊れたか追跡がしにくくなりそう。
マージキューの方がよさげ。

**Comment by yonta** [comment]
いやいや、キューよりcancelだね。

今回のように複数のデプロイ要求が連続できたらどうすべきか。
僕は古いデプロイを捨てて、新しいほうを優先すべきだと思う。
そもそも順番にやっていくと、古いデプロイはすぐに上書きされるから。

ただし、古いデプロイが失敗しないという前提。
これはすでにCIやPRでのみmasterへの許可、という設定から叶っていると思う。

マージキューはキューなので、デプロイはただ順番に行われるだけでしょ？
つまい古いデプロイを時間をかけて行う。
でもキューに入っていた新しいデプロイですぐにこの古いデプロイは上書きされてしまう。
新しいデプロイ機能が来るのが遅れる。

一方で、skip-duplicate-actionにはcancel otherという、新しいやつで古いのをキャンセルする機能がある。
これを使えば、新しいデプロイが開始されたときに、すでに動いている古いデプロイを即止めることができる。

たぶんこれが一番いいと思います。

**Comment by yonta** [comment]
いや待てよ、”マージ”キューだから、複数Actionsに対するマージ方法も設定できるのか？

**Comment by yonta** [comment]
マージキュー使うことで、「CI成功したときにのみ、deployする」みたいなのができそうだけど、違うのかな。
我々でいうと、ほしいのは「masterブランチでtest/checkを成功したらfly-deploy」を走らせる、みたいなの。

うーん、ドキュメントの情報量が少なくてできるかよくわからない。

**Comment by yonta** [comment]
やはりマージキューだな！！！

**Comment by yonta** [comment]
マージキュー完全に理解した。

マージキュー自体は複数PRを同時に受け入れると、メインブランチの更新やPR同士の変更で、マージ結果のチェックが通らないのを防ぐ機能なんだね。
例えば、

1. main1にPR1を出す（Checkが通る）
2. main1にPR2を出す（Checkが通る）
3. PR1を受け入れる、main1がPR1でmain2に更新される
4. PR2を受け入れる、main2がPR2でmain3に更新される
5. PR1とPR2の変更が合わさってCheckが通らない

みたいな場合を防げる。

具体的には、PRを受け入れるときに、「マージ」ではなく「マージキューに追加」を行うことになる。
するとGitHubが次のようにしてくれる。

1. main1にPR1を出す（Checkが通る）
2. main1にPR2を出す（Checkが通る）
3. PR1を受け入れマージキューに追加する（mainの変更とともに、改めてCheckを通してからマージする）
4. PR2を受け入れマージキューに追加する（mainの変更、マージキューにあるPR1の変更を含めて、改めてCheckを通してからマージする）
5. PR1とPR2の変更が合わさってCheckが通らない場合は、マージがブロックされmainが保護される

**Comment by yonta** [comment]
このIssueの問題点に立ち返ると、問題は「連続したDeploy行われるとDeployが失敗する」。
マージキューとは違う機能に見える。

けど、マージキューには「同時にベース ブランチにマージする pull request の最小数と最大数」って設定がある。

> マージする pull request の最大数
> グループの最大サイズを指定できます。これは、ベース ブランチへのマージによってデプロイがトリガーされ、一度にデプロイする変更が多すぎないようにする場合に役立ちます。

この最大数を1にセットしておけば並列デプロイ実行によりデプロイが壊れるのを防げそう！

**Comment by yonta** [comment]
マージキューを使えば、Deploy連打でDeployの失敗を止められそう。
しかも並列PRで思わぬmainブランチがCheck通らなくなって壊れるのを防げる。
うおー、やるぞ！

**Comment by yonta** [comment]
Fly DeployとTestとCheckが違うワークフローになってるから、ワークフローの再利用が必要そう。

**Comment by yonta** [comment]
トリガー`pull_requrest`ってPRで追加のpushでも走るし、`push`でActions走らせなくてもいい気がしてきた。
PRになってないブランチにも走ってくれるのは便利だけど、Actions走らせたいときはドラフトPRにしたら走るし。

**Comment by yonta** [comment]
マージキューはエンタープライズプランじゃないと使えないとのこと。
リッチな機能てんこ盛りですものね。

**Comment by yonta** [comment]
- concurrency groupを定義することで、同じグループのジョブは１つに制限される。
- concurrencyの指定はトップレベルですべてのJOBに指定するか、JOB内で特定JOBへ指定できる
- group名には固定文字列と変数込みの文字列が使える
  - 固定なら唯一のJOBとできる
  - 変数を含めれば、例えば特定のブランチを対象にして、や、あるコミット対象のJOBは1つまで、などが実現できる
  ‐ 他にも、`||`でフォールバックという機能があり、複数変数マッチなど複雑な計算ができる
- `cancel-in-progress`を設定することで、キューにあるJOB操作を指示できる
  - `true`なら、JOB1実行中にJOB2がきたら、JOB1はキャンセルされてJOB2が実行される
  - `false`または指定なしなら、JOB2の実行はペンディングされ、JOB1の終了を待つ
  - ここに式を適用もでき、特定のブランチでのみtrue、デフォルトはfalseみたいなことも書ける

**Comment by yonta** [comment]
Fly Deployのジョブに固定文字列concurrency groupを設定すれば、やりたいことが実現できそうだ！

**Comment by yonta** [comment]
## `cancel-in-progress`をどうするか問題

- `true`なら
  - 新しいJOBが優先され、新機能のマージがなるべく早くデプロイされる
- `false`なら
  - 古いJOBが優先され、デプロイは確実にすべて行われる
  - もしデプロイが失敗したときに、どこで壊れたかが特定しやすくなる
