### ISSUE TITLE
docker compose buildに時間がかかる

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#617]
docker compose buildするときに.dockerignoreに従ってディレクトリがロードされる
しかし今ある.dockerignoreはfly deploy用。devのときにこの.dockerignoreが読み込まれるせいで、docker compose buildに時間がかかるんじゃないかと推測している。

**Comment by yonta** [comment]
タイトルだと正しいことに見えるので、何が間違っているかをタイトルに書くといいよ

**Comment by yonta** [comment]
あとルー語っぽくなってる…

**Comment by momocus** [comment]
タイトル変えました

**Comment by momocus** [comment]
特に何もしてないけど、昨日buildしたとき爆速だったわ
