### ISSUE TITLE
IssueテンプレートにEOLがないため、masterのCheckが落ちている

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#645]
## 何が起きている

CIのCheckがmasterの最新コミットで落ちている。

https://github.com/momocus/sakazuki/commit/8dc41abf640b51f3c64dd1981a1b8b412cedc82c

## 原因

該当コミットはこれ

https://github.com/momocus/sakazuki/commit/8dc41abf640b51f3c64dd1981a1b8b412cedc82c

**Comment by momocus** [comment]
ごめんなさいごめんなさい
とり急ぎrevertしました
