### ISSUE TITLE
プルリク出した人が自動でAssigneesに設定されるようにしたい

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#658]
## Why/ 背景

Assignees設定されてないともやっとする。
Assignees設定されてると通知がきていい。

## What/ 何をしたいか

プルリク出した人が自動でAssigneesに設定されるようにする

## How/ どうやって実現するか

これから調べる

**Comment by exoego** [comment]
https://github.com/marketplace/actions/auto-assign-action

> Add the PR creator as the assignee of the pull request.
> 
> ```
> # Set addAssignees to 'author' to set the PR creator as the assignee.
> addAssignees: author
> ```

**Comment by yonta** [comment]
https://docs.github.com/ja/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team
ひょっとしてTeam設定すればActionsいらなかった説
