### ISSUE TITLE
deviseがalert上げるときにbootstrapを使う

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#66]
deviseがアラートを上げるとき、メッセージタイプが`alert`とかなのは変更できないかな？
例えば、現状だとロックされたというメッセージが`class="alert alert-alert"`となり、bootstrapから扱いづらい。

あと1回でロックされる、ロックされてるは両方とも`alert alert-warning`あたりだと良さそう。
ログインログアウトは`alert alert-info`とかだと良さそう。

- app/views/layout/application.html
```erb
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
```

[bootstrapのAlert一覧](https://getbootstrap.jp/docs/4.5/components/alerts/)

_Originally posted by @yonta in https://github.com/momocus/sakazuki/pull/64#issuecomment-670347587_

**Comment by momocus** [comment]
この方法でできそう
https://hachy.github.io/2019/10/15/flashes-with-devise-and-bootstrap.html

**Comment by yonta** [comment]
すでに修正済み
