### ISSUE TITLE
新規酒登録の画像は最上部にする

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#724]
## Why/ 背景

今の登録の流れ

- カメラアプリで写真を撮る
- 酒を登録する（名前、…、写真の順）

特に複数同時登録だと、

- カメラアプリ
  - 酒1の写真
  - 酒2の写真、…
- 酒登録
  - 名前（このとき、どれを登録するのか決まってなく違和感。結局、画像を先に選ぶ）
  - 画像選び

## What/ 何をしたいか

カメラアプリが先になりがち。
登録するのも画像が先のほうがよい。

## How/ どうやって実現するか

順番をかえる

**Comment by yonta** [comment]
## モバイルの新規

![image](https://github.com/momocus/sakazuki/assets/849256/49f41bd9-0f53-415b-9555-9d5a61ede539)

**Comment by yonta** [comment]
どうかなぁ。意見を聞きたい @momocus

**Comment by momocus** [comment]
@yonta 画像が先、いいと思う！　
酒のスペックが書かれたラベルの写真を先に登録して、あとから写真見ながら情報を足す、という使い方もやりやすくなって良いと思いました。

（OCRが無限にできる世界線に行けたら、画像登録しただけで酒のスペック自動入力できるようにしたい)

**Comment by yonta** [comment]
わかる、OCRで楽したい…。
でもOCRが辛い。
