### ISSUE TITLE
Bug: `Only in Stock`のフィルターが機能していない

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#75]
Oops

![image](https://user-images.githubusercontent.com/849256/90490547-b740ef80-e179-11ea-9d7a-aaa689de5824.png)

**Comment by momocus** [comment]
テキスト検索も死んでた
![image](https://user-images.githubusercontent.com/6294782/90621980-73201e80-e24f-11ea-979f-a3d360da8adb.png)
