### ISSUE TITLE
ログインしたあとの画面をログインフォーム移動前の画面にする

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#90]
### 現在の動作

- ログインせずにトップページへ行く
- 酒をshowする
- 酒を編集しようとする
- ログイン画面に飛ばされ、ログインする
- ログイン後トップページに戻される

### 期待する動作

- 酒編集でログインしたので、ログイン後は酒の編集画面になってほしい

**Comment by momocus** [comment]
closed this in #197
