### ISSUE TITLE
sakes/newでエラーするとsakesにリダイレクトされている

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#96]
### 問題点

- 酒登録でエラーしたときにF5更新すると、トップページに戻されてしまう
- 場合によっては登録していた途中入力が吹っ飛ぶ
- 同様の問題がuser/editでも起こっており、エラーするとURLがユーザになりこのままF5するとルーティングエラーになる

### 再現手順

1. 新規の酒登録画面にいく
    - 例えば、URLは`http://localhost:3000/sakes/new`
2. 名前無しで登録ボタンを押してエラーを起こす
3. URLがnewでなくなる
    - 例えば、URLが`http://localhost:3000/sakes`

![image](https://user-images.githubusercontent.com/849256/100584177-17c1fa00-332f-11eb-8e3b-882a8e33b0e9.png)

**Comment by momocus** [comment]
仕様みたい。
https://stackoverflow.com/questions/58043429/why-is-render-new-changing-my-url-ruby-on-rails

**Comment by momocus** [comment]
めも

new アクションは/sakes/newへのGET
createアクションは/sakesへのPOST

酒登録でValidation errorがあると、createアクションでrender newされる。
renderはビューを変えるだけでURLは変えないため、URLはcreateアクションに対応する/sakesのままになる。

**Comment by momocus** [comment]
エラーの有無関係なく、newやedit画面でリロード（F5）したときにどうすべきだろう？
「このページを離れますか？　編集途中の内容は失われます」とか警告だすのがいい気がする。

**Comment by yonta** [comment]
ブラウザの基本動作としてリロードでは入力内容は失われない。
ただし、今は酒の名前に`autocomplete=off`つけたから、ここだけ失われる。
そう考えると、多少邪魔でも名前の`autocomplete=off`を削除したほうがいいかも。

**Comment by yonta** [comment]
今はそもそもブラウザの機能で名前の空を許さなくしてあるので、この問題はおきない。

![image](https://user-images.githubusercontent.com/849256/220289316-b8e94dce-5df9-4f30-9a72-5c461fde033a.png)
